### ISSUE TITLE
LONG REGENERATION!

### ISSUE THREAD

**Issue by Psychothekid** [GamersNetworkMC/Issues#33]
My heart doesn't seem to regenerate. My hunger bar is full too. I played in Frozen Tears. Is it only this map or all?

**Comment by morpig** [comment]
Under Investigation. Will reply ASAP

**Comment by morpig** [comment]
Fix on GamersNetworkMC/SurvivalGames-v2@5b95cf02b24f65a1213aed2f0b2742304d4e9e3e
